public enum CarPartType
{
    FrontFenderLeft,
    FrontFenderRight,
    FrontDoorLeft,
    FrontDoorRight,
    RearDoorLeft,
    RearDoorRight,
    SteeringWheel,
    Seat,
    Engine,
    Battery,
    Trunk,
    RearBumper,
    Hood,
    FuelTank,
    WheelFrontLeft,
    WheelFrontRight,
    WheelRearLeft,
    WheelRearRight
}
